config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [:new, :create, :index, :show] do
    resources :doses, only: [:new, :show, :create]
  end

  resources :doses, only: [:destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cocktail.rb
class Cocktail < ApplicationRecord
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  validates :name, uniqueness: true, presence: true
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient, dependent: :destroy
  validates :description, presence: true
  validates :cocktail, uniqueness: { scope: :ingredient }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  has_many :doses
  validates :name, uniqueness: true, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cocktails_controller.rb
class CocktailsController < ApplicationController
  def index
    @cocktails = Cocktail.all
  end

  def show
    @cocktail = Cocktail.find(params[:id])
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)

      if @cocktail.save
        redirect_to @cocktail, notice: 'Cocktail was successfully created.'
      else
        render :new
      end
  end

  private
  def cocktail_params
    params.require(:cocktail).permit(:name)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  def new
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new
  end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail

    if @dose.save 
      redirect_to cocktail_path(@cocktail)
    else
      render :new
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private
  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cocktails_helper.rb
module CocktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/cocktails/_form.html.erb
<%= simple_form_for(@cocktail) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
  </div>

  <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/cocktails/index.html.erb
<h1>Cocktails</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Action</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cocktails.each do |cocktail| %>
      <tr>
        <td><%= cocktail.name %></td>
        <td><%= link_to 'Show', cocktail %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Create new Cocktail', new_cocktail_path %>

app/views/cocktails/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-md-8">
        <h1>Create a new Cocktail</h1>
        <%= render 'form', cocktail: @cocktail %>
        <%= link_to 'Back', cocktails_path %>
    </div>
  </div>
</div>

app/views/cocktails/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @cocktail.name %>
</p>

<div class="row">
    <div class="col-sm-12 col-md-6">
      <h3>Recipe</h3>
      <table class="table table-bordered">
        <tbody>
          <thead>
            <th>Ingredient</th>
            <th>Description</th>
            <th>Action</th>
          </thead>
          <% @cocktail.doses.each do |dose| %>
           <tr>
            <td><%= dose.ingredient.name %></td> 
            <td><%= dose.description %></td> 
            <td>
              <%= link_to "🗑 delete", dose_path(dose), method: :delete, data: { confirm: "Are you sure?" } %>          <% end %>
            </td>
           </tr> 
        </tbody>
      </table>
    </div>
</div>



<%= link_to 'Back to all cocktails', cocktails_path %> | 
<%= link_to 'Add dose', new_cocktail_dose_path(@cocktail) %>

app/views/doses/new.html.erb
<h1>Add a new ingredient/description pair for <%= @cocktail.name %></h1>

<%= simple_form_for([@cocktail, @dose]) do |f| %>
  <%= f.input :description %>
  <%= f.association :ingredient %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>